### ISSUE TITLE
Implement Classic Login Page

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [blossomlabsio/bloom#14]
We are using ReactTS in frontend and FastAPI for backend. We want to add Classic Login Page to our React app so that users can login to our website.

**Comment by RahulMittal18** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can help implement it. Thanks!

**Comment by Mr-Sunglasses** [comment]
Hey, @RahulMittal18, thanks for your interest in this issue. Currently, this issue is no longer a hacktoberfest issue, cause we are creating our own API endpoint in the backend to implement it, so this issue can be only assigned to our internal team, In the meantime, you can browse other issues.
