### ISSUE TITLE
Update NavBar Login Button Behavior for Login/Logout Functionality

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [blossomlabsio/bloom#26]
We have a Login button on NavBar. On successful login, change the text of the Login button to Logout and on clicking the Logout button, redirect to the home page.

**Comment by gautam-bhagat** [comment]
Hii Shreya,
You can assign the issue to me. I'm sure the functionality will be done quickly

**Comment by ShreyaPrasad1209** [comment]
@gautam-bhagat can you create a draft PR? Post that I'll assign this issue to you.
